export { default as HomeLayout } from './HomeLayout'
export { default as Register } from './Register'
export { default as Login } from './Login'
export { default as Error } from './Error'
export { default as Meals } from './Meals'
export { default as SingleMeal } from './SingleMeal'
export { default as Checkout } from './Checkout'
export { default as Orders } from './Orders'
export { default as AddMeal } from './AddMeal'
export { default as UpdateMeal } from './UpdateMeal'
export { default as Profile } from './Profile'
export { default as Admin } from './Admin'
export { default as ChangePassword } from './ChangePassword'
export { default as Blog } from './Blog'
export { default as Cart } from './Cart'
export { default as DeleteMeal } from './DeleteMeal'
export { default as Landing } from './Landing'
export { default as SingleOrder } from './SingleOrder'
export { default as OrderSuccess } from './OrderSuccess'
export { default as CreateReminder } from "./CreateReminder"
export { default as Reminders } from "./Reminders"
export { default as SingleBlog } from "./SingleBlog"
export { default as AdminMeals } from "./AdminMeals"
export { default as AdminBlog } from "./AdminBlog"
export { default as AdminCart } from "./AdminCart"
export { default as AdminOrders } from "./AdminOrders"
export { default as AdminReminders } from "./AdminReminders"
export { default as AdminReviews } from "./AdminReviews"
export { default as AdminLogin } from "./AdminLogin"
export { default as AdminUsers } from "./AdminUsers"
export { default as AdminDashboard } from "./AdminDashboard"
